# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t0mjVbY-2BZ1AuN8nRdSeKx2okuHK8Y6
"""

from flask import Flask, request, jsonify
from joblib import load

pipeline = load('pipeline.pkl')

# Creamos la apliación Flask
app = Flask(__name__)

@app.route('/predict', methods=['GET', 'POST'])
def predict():

    data = request.json

    prediction = pipeline.predict(data)

    return jsonify(prediction.tolist())

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)